apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: abdopython2001-dev
  labels:
    app: tools-project-app  # Correct the label for the app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: node:16-alpine  # Use a Node.js image to install dependencies and build the app
          command: ["sh", "-c", "npm install && npm run build && npx http-server ./build -p 8080"]
          ports:
            - containerPort: 8080  # Expose the port for the React app
          volumeMounts:
            - name: app-source
              mountPath: /usr/src/app
      volumes:
        - name: app-source
          gitRepo:
            repository: "https://github.com/abdogith/ToolsProject"  # Replace with your Git repo URL
            revision: master  # or the branch you want to deploy

